### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by bryan-kc** [lbrndnr/spotit#1]
Hi, I'm trying to use your script to generate a playlist. I have acquired a spotify API key and secret.

When I run the script for the first time it throws the following error, and if i run it again after the error it will not have an error (likely because the file alltracks.p exists)

It seems like `playlist` is of type None when `sp.user_playlist_add_tracks` is called. Any advice on debugging so that playlist is not None and the tracks are added? 

```
python3 -i spotit.py -r electronicmusic -su bubblepenguin -ru methionine
Version 3.6.0 of praw is outdated. Version 4.0.0 was released 5 hours ago.
['1TFkQqDjfFazRJbrRwYOf4', '2w7pHPE7Ak0zc4keLZ2clK', '3HiZwJJKs5b9B47JwzwhVj', '05j1HlBne0W7fNVjYPGOT1', '6ssrBC8UBchaQVtwmUXsIa', '2v6NosEeFeXZxeW5GF3yHH', '6reg46TnVrrHBEpV4H9yZN', '46frEscYLoQ483ZjvmlmbE', '6VcVJ7YddkP6elt9Ym8c50', '6Xdg1QsEzirCM0QA9Wzp8L', '1zH9vH7G0DDizjKlmZxUy9', '4AT05mcqWpi5ocehqP56zB']
None
Traceback (most recent call last):
  File "spotit.py", line 149, in <module>
    update_playlist(subreddit, sp_username, re_username, token, "alltracks.p")
  File "spotit.py", line 129, in update_playlist
    sp.user_playlist_add_tracks(sp_username, playlist["id"], new_tracks)
TypeError: 'NoneType' object is not subscriptable

**Comment by lbrndnr** [comment]
I think you are using an outdated commit, try using the latest one :)

**Comment by bryan-kc** [comment]
Hi,

I pulled the latest commit from 4 hours ago (https://github.com/lbrndnr/spotit/commit/7ec4f1cb06ad12204bd3b9c63665a257c9bc664f) and it appears you removed the main method. 

How would someone invoke the script now? The instructions in the readme would only load up the function definitions.

**Comment by lbrndnr** [comment]
Yeah sorry, I removed it because it basically required too many parameters to be practical from the command line.
I basically wrote an additional script that imports spotit, fetches the access token and then invokes the `update_playlist` method. I'll update the README in a bit.
